name = "schemamap"
compatibility_date = "2024-01-01"

[site]
bucket = "./apps/web/out"

[build]
command = "pnpm install && pnpm --filter @schemamap/engine build && pnpm --filter @schemamap/web build"

[[build.upload]]
format = "service-worker"

[env.production]
route = "schemamap.com/*"